<?php include 'header.php'; ?>
		<div class="section section-breadcrumbs">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<h1>Site Policy & Listing Service Use</h1>
					</div>
				</div>
			</div>
		</div>
        
        <div class="section">
	        <div class="container">
	        	<p>PLEASE READ THIS TERMS OF SERVICE AGREEMENT CAREFULLY. YOU SHOULD REVIEW THIS AGREEMENT EACH TIME YOU VISIT THIS SITE OR USE ANY SERVICES. IF YOU DO NOT AGREE TO THESE TERMS (INCLUDING ANY REFERENCED POLICIES OR GUIDELINES), YOU MUST IMMEDIATELY TERMINATE YOUR USE OF ANY PORTION OF THE SITE OR SERVICES. IF YOU WOULD LIKE TO PRINT THIS AGREEMENT, PLEASE CLICK THE PRINT BUTTON ON YOUR BROWSER TOOLBAR.</p>
	        	<p>&nbsp;</p>
	        	<p><b>1. Acceptance Triggered by Use.</b></p>
	        	<p>This Terms of Service and Use Agreement (the "Agreement") is between you and Akimoto Ventures, LLC ("Lease Office Space"), a Texas Corporation, and governs your access and use of this web site (the "Site"). The Agreement is subject to change, and we will make those changes by posting the new Agreement on the Site. Your continued use of the Site will constitute your acceptance of any changes or revisions.</p>
	        	<p><b>2. Grant of Limited License.</b></p>
	        	<p>The proprietary software, content, and materials underlying the Site (the "Materials") are works protected under copyright and other intellectual property laws. In consideration for your promises reflected in this Agreement, you are granted a personal, nonexclusive, nonassignable and nontransferable, non-commercial license to access and use the Site from a single computer and as permitted under this Agreement.</p>
	        	<p>You agree to: (i) not copy or distribute the Materials to any third party; (ii) not reverse engineer, disassemble or decompile any portion of the Materials or otherwise attempt to discover or re-create the source code to the Materials; (iii) comply with all applicable laws, including U.S. export control laws, applicable to your use of the Materials; (iv) not make any modification, adaptation, improvement, enhancement, translation, or derivative work of or to any portion of the Materials; (v) not remove, alter, or obscure any proprietary notices in any portion of the Materials or on the Site; (vi) not interfere with or disrupt the use and enjoyment of the Site by other users; and (vii) not use any type of automated means to utilize or access the Site.</p>
	        	<p><b>3. User Submitted Content; Consent to Aggregate Information on Your Behalf.</b></p>
	        	<p>A. The Site enables you to aggregate, post and publish relevant information, data, images and pictures you wish to include in our database (e.g., office space listings and associated images and pictures). You acknowledge and agree that on your behalf, we may aggregate, post and publish such relevant information and data upon your (1) usage of the content submission/update tools within the Site, (2) acknowledgement of, and agreement to, the provisions of this Agreement, (3) emailing property marketing flyers, advertisements or other marketing materials to us, (4) emailing us (or identifying/confirming) the URL(s) which contain information you are authorized to share, (5) responding to a tenant inquiry originating from us, (6) giving us verbal, written, click-wrap or browse-wrap permission to include your information and content in the database, (7) granting approval in response to queries, including via email from us or third parties, (8) confirming or claiming information we may have with respect to your information and data, or (9) by submitting or approving data or information for inclusion through any other means, whether express or implied. Such information and content which you authorize us to collect is collectively referred to as "User Provided Content". By way of example and not limitation, if you are a broker with an office space listing on the Site, and you supply to us URLs or otherwise identify/confirm URLs which contain information and data with respect to your office space listing, you acknowledge and agree that we may aggregate and include such information on your behalf in our database for publishing on the Site. You understand that we do not guarantee any confidentiality with respect to any User Provided Content. The fact that we seek permission from you for inclusion of certain data or information is not to be construed as an acknowledgment that such data or information is protectable by copyright or other laws.</p>
	        	<p>B. You shall be solely responsible for your own User Provided Content and the consequences of posting or publishing them. You affirm, represent, and/or warrant that you own or have all the necessary licenses, rights, consents, and permissions to use and authorize Lease Office Space to use all patent, trademark, trade secret, copyright or other intellectual property or proprietary rights in and to any and all User Provided Content you submit to enable inclusion and use of the User Provided Content in the manner contemplated by the Site and this Agreement.</p>
	        	<p>C. For clarity, you retain ownership of all copyrights you may have in your User Provided Content. However, by submitting User Provided Content to Lease Office Space, you hereby grant Lease Office Space a perpetual, irrevocable, worldwide, non-exclusive, royalty-free, sub-licenseable and transferable license to use, adapt, advertise, modify, market, sell, reproduce, distribute, prepare derivative works of, display, and perform the User Provided Content (in whole or in part), for any purpose whatsoever, and to incorporate User Provided Content in other works in any form, media, or technology now known or later developed. The foregoing license shall be broadly construed, and shall include, without limitation the right to: (i) promote and redistribute part or all of the User Provided Content (and derivative works thereof) in any media formats and through any media channels, (ii) incorporate the User Provided Content on tangible or intangible products for resale or otherwise, and (iii) use the User Provided Content for promotional purposes, whether to promote the Site, other Lease Office Space products or services, or third party products or services. By way of clarification and not limitation, you acknowledge that you will not be entitled to any royalties or any other payment as a result of any efforts by Lease Office Space to exploit any User Provided Content. By way of further clarification, Lease Office Space may freely sublicense the rights that you grant it in this Section to a third party. To the extent necessary for Lease Office Space to exercise its rights under the foregoing license, you hereby grant Lease Office Space a perpetual, royalty-free and irrevocable license to exploit any personality, publicity, or privacy rights in and to the User Provided Content and in your likeness as contained therein. You also hereby grant each user of the Site a non-exclusive license to access your User Provided Content through the Sites, and to use, reproduce, distribute, display and perform such User Provided Content as permitted through the functionality of the Sites and under these Terms of Service.</p>
	        	<p>D. In connection with User Provided Content, you further agree that you will not submit material that is copyrighted, protected by trade secret or otherwise subject to third party proprietary rights, including privacy, personality and publicity rights, unless you are the owner of such rights or have permission from their rightful owner to post the material and to grant Lease Office Space all of the license rights granted herein.</p>
	        	<p>E. Lease Office Space does not endorse any User Submission or any opinion, recommendation, or advice expressed therein, and Lease Office Space expressly disclaims any and all liability in connection with User Provided Content. Lease Office Space does not permit copyright infringing activities and infringement of intellectual property rights on its Site, and Lease Office Space will remove all Content and User Provided Content if properly notified in a manner consistent with law and Lease Office Space's Copyright Infringement Notification Policy (see below) that such Content or User Submission infringes on another's intellectual property rights. Lease Office Space reserves the right to remove User Provided Content without prior notice.</p>
	        	<p><b>4. Privacy Policy.</b></p>
	        	<p>You can find information regarding our policies regarding information collection at <a href="https://leaseofficespace.net/privacy.php">https://leaseofficespace.net/privacy.php</a>.</p>
	        	<p><b>5. NO WARRANTIES - SITE PROVIDED "AS IS".</b></p>
	        	<p>YOU UNDERSTAND AND AGREE THAT THE SITE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. YOU EXPRESSLY AGREE THAT USE OF THE SITE IS AT YOUR SOLE RISK.</p>
	        	<p>TO THE FULLEST EXTENT PERMISSIBLE UNDER THE APPLICABLE LAW, WE DISCLAIM ALL WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO, WARRANTIES OF TITLE, OR IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. WITHOUT LIMITING THE FOREGOING, NEITHER US NOR ANY OF OUR AFFILIATES OR LICENSORS, NOR ANY OF THEIR OFFICERS, DIRECTORS, LICENSORS, EMPLOYEES OR REPRESENTATIVES REPRESENT OR WARRANT (i) THAT THE SITE WILL MEET YOUR REQUIREMENTS OR BE ACCURATE, COMPLETE, RELIABLE, OR ERROR FREE; (ii) THAT THE SITE WILL ALWAYS BE AVAILABLE OR WILL BE UNINTERRUPTED, ACCESSIBLE, TIMELY, OR SECURE; (iii) THAT ANY DEFECTS WILL BE CORRECTED, OR THAT THE SITE WILL BE FREE FROM VIRUSES, "WORMS," "TROJAN HORSES" OR OTHER HARMFUL PROPERTIES; (iv) THE ACCURACY, RELIABILITY, TIMELINESS, OR COMPLETENESS OF ANY MATERIAL PUBLISHED OR ACCESSIBLE ON OR THROUGH THE SITE; (v) ANY IMPLIED WARRANTY ARISING FROM COURSE OF DEALING OR USAGE OF TRADE; AND (vi) THAT THE MATERIALS ARE NONINFRINGING.</p>
	        	<p>YOU ACKNOWLEDGE AND AGREE THAT THE SERVICES OR CONTENT OBTAINED THROUGH THE USE OF THE SITE ARE DONE AT YOUR OWN DISCRETION AND RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE, INCLUDING TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM YOUR USE OF THE SITE, SERVICES, OR ANY MATERIALS.</p>
	        	<p><b>6. LIMITATION OF LIABILITY.</b></p>
	        	<p>IN NO EVENT SHALL WE OR ANY OF OUR AFFILIATES OR LICENSORS, OR ANY OF THEIR OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, REPRESENTATIVES, INFORMATION PROVIDERS OR LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE OR OTHER DAMAGES (REGARDLESS OF THE FORM OF ACTION) ARISING OUT OF (i) USE OF THE SITE BY ANY PERSON, INCLUDING BUT NOT LIMITED TO, ANY DAMAGE CAUSED BY ANY RELIANCE ON, OR ANY DELAYS, INACCURACIES, ERRORS OR OMISSIONS IN, ANY INFORMATION AND CONTENT ACCESSED OVER THE SITE, (ii) ANY USE OR INABILITY TO USE THE SITE FOR WHATEVER REASON, INCLUDING BUT NOT LIMITED TO COMMUNICATIONS FAILURE OR ANY OTHER FAILURE WITH TRANSMISSION OR DELIVERY OF ANY INFORMATION ACCESSED THROUGH THE SITE, OR (iii) ANY GOODS OR SERVICES DISCUSSED, PURCHASED OR OBTAINED, DIRECTLY OR INDIRECTLY, THROUGH THE SITE OR OTHERWISE, IN EACH CASE EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
	        	<p>SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES. ACCORDINGLY, SOME OF THE ABOVE LIMITATIONS AND EXCLUSIONS MAY NOT APPLY TO YOU.</p>
	        	<p><b>7. Termination.</b></p>
	        	<p>Your rights under this Agreement terminate automatically if you fail to comply with any of the terms and conditions of this Agreement or with any other policy or rule. Additionally, we may terminate this Agreement at any time and for any reason. We may effect notice of termination through any means, including but not limited to posting such notice on the Site, sending you an email, or otherwise proclaiming such termination. Upon termination, you must immediately stop using the Site. We have no obligation to return any materials you provide to us in the course of using the Site.</p>
	        	<p><b>8. Indemnification Obligations.</b></p>
	        	<p>You agree to hold harmless, defend, and indemnify us and our licensees, licensors and their officers, directors, employees, subsidiaries, contractors, subcontractors, suppliers, agents, partners and affiliates, successors and assigns from all liabilities, claims, demands and expenses, including attorney's fees, that are due to, or that arise from your use or misuse of the Site, any Users Provided Content, or content transmitted to or through the Site, or for infringement by you of intellectual property rights or other right of any third party. We may assume exclusive control of any defense of any matter subject to indemnification by you, and you agree to cooperate with us in such event.</p>
	        	<p><b>9. Third Party Links and/or Content.</b></p>
	        	<p>We do not endorse and are not responsible or liable for any content, advertising, goods or services, or other materials available on or from any third party web sites or resources.</p>
	        	<p><b>10. Feedback.</b></p>
	        	<p>Any comments or materials sent to us, including feedback data, such as questions, comments, suggestions, or the like regarding the Site is non-confidential. We have no obligation to you of any kind with respect to such feedback and are free to reproduce, use, disclose, exhibit, display, transform, create derivative works and distribute the feedback to others without limitation.</p>
	        	<p><b>11. Notices; Announcements.</b></p>
	        	<p>We may provide notices, including notice of any changes to this Agreement by displaying notices to you generally on the Site or by emailing you at the email address you provided us. We may change our addresses (email or mailing) by displaying such changes on the Site. Except as set forth herein, you must provide us all notices in writing, delivered to the street address listed on the "contact us" page. Notwithstanding, we will endeavor to respond to any emails you send raising any concerns or questions.</p>
	        	<p><b>12. Copyright Infringement Notification Policy.</b></p>
	        	<p>Lease Office Space respects the intellectual property rights of others. If you believe that your work has been copied in a way that constitutes copyright infringement by any content or material on the Site, please provide the following information in writing to Lease Office Space's copyright agent (see 17 U.S.C. Section 512(c)(3) for further detail):</p>
	        	<ol>
	        	<li>A physical or electronic signature of a person authorized to act on behalf of the owner of the copyright.</li>
	        	<li>A description of the copyrighted work that you claim has been infringed.</li>
	        	<li>A description of the material that you claim to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information sufficient to permit us to locate the material.</li>
	        	<li>Information so that we can contact you, such as address, telephone number and e-mail address.</li>
	        	<li>A statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law.</li>
	        	<li>A statement that the information in the notification is accurate and, under penalty of perjury, that you are the copyright owner or are authorized to act on behalf of the owner of a copyright that is allegedly infringed.</li>
	        	</ol>
	        	<p>If you believe that any content or materials you posted, uploaded or Submitted to the Site, that were subsequently removed from the Site, or to which access was disabled, were improperly removed or disabled, please provide the following Counter-Notification to Lease Office Space's copyright agent (see 17 U.S.C. Section 512(g) for further detail):</p>
	        	<ol>
	        	<li>your physical or electronic signature.</li>
	        	<li>a description of the materials that have been removed or to which access has been disabled and the location at which the material appeared before it was removed or access to it was disabled.</li>
	        	<li>a statement under penalty of perjury that you have a good faith belief that the material was removed or disabled as a result of mistake or misidentification of the material to be removed or disabled.</li>
	        	<li>your name, address and telephone number, and a statement that you consent to the jurisdiction of the Federal District Court for the judicial district in which the address is located, and that you will accept services of process from the person who provided notification of the alleged infringement.</li>
	        	</ol>
	        	<p>Lease Office Space's copyright agent can be reached as follows:<br /><br /><a href="mailto:info@leaseofficespace.net">info@leaseofficespace.net</a></p>
	        	<p>Only DMCA notices should be sent to the copyright agent. For other comments or questions regarding the Site, please contact us through our contact page.</p>
	        	<p><b>13. Legal Disputes - Arbitration.</b></p>
	        	<p>You agree that any claim or dispute at law or equity that has arisen or may arise between you and Lease Office Space relating in any way to or arising out of this or previous versions of the Agreement, your use of or access to the Site, or any services, applications, and tools, or any products or services sold or purchased through the Site (each a "Dispute") will be resolved in accordance with the provisions set forth in this Legal Disputes Section (the "Agreement to Arbitrate").</p>
	        	<p>Please read this Section carefully. It affects your rights and will have a substantial impact on how claims you and we have against each other are resolved.</p>
	        	<p>13.1 Applicable Law. You agree that the laws of the State of Texas, without regard to principles of conflict of laws, will govern the Agreement and any Dispute.</p>
	        	<p>13.2 Agreement to Arbitrate. You agree that any Disputes shall be resolved exclusively through final and binding arbitration, rather than in court. The Federal Arbitration Act governs the interpretation and enforcement of this Agreement to Arbitrate.</p>
	        	<p>13.3 Prohibition of Class and Representative Actions and Non-Individualized Relief. YOU AND Lease Office Space AGREE THAT EACH OF US MAY BRING CLAIMS AGAINST THE OTHER ONLY ON AN INDIVIDUAL BASIS AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE ACTION OR PROCEEDING. UNLESS BOTH YOU AND Lease Office Space AGREE OTHERWISE, THE ARBITRATOR MAY NOT CONSOLIDATE OR JOIN MORE THAN ONE PERSON'S OR PARTY'S CLAIMS, AND MAY NOT OTHERWISE PRESIDE OVER ANY FORM OF A CONSOLIDATED, REPRESENTATIVE, OR CLASS PROCEEDING. ALSO, THE ARBITRATOR MAY AWARD RELIEF (INCLUDING MONETARY, INJUNCTIVE, AND DECLARATORY RELIEF) ONLY IN FAVOR OF THE INDIVIDUAL PARTY SEEKING RELIEF AND ONLY TO THE EXTENT NECESSARY TO PROVIDE RELIEF NECESSITATED BY THAT PARTY'S INDIVIDUAL CLAIM(S). ANY RELIEF AWARDED CANNOT AFFECT OTHER Lease Office Space USERS.</p>
	        	<p>13.4 Arbitration Procedures. The arbitrator, and not any federal, state,  local court or agency, shall have exclusive authority to resolve any Dispute, any part of it, including, but not limited to, any claim that all or any part of the Agreement to Arbitrate or Terms is void or voidable.</p>
	        	<p>The arbitration will be conducted by the American Arbitration Association ("AAA") under its rules and procedures, including the AAA's Supplementary Procedures for Commercial Disputes (as applicable), as modified by this Agreement to Arbitrate.</p>
	        	<p>The arbitration shall be held in Dallas County, Texas or at another mutually agreed location. If the value of the relief sought is $10,000 or less, you or Lease Office Space may elect to have the arbitration conducted by telephone or based solely on written submissions, which election shall be binding on you and Lease Office Space, subject to the arbitrator's discretion to require an in-person hearing, if the circumstances warrant. Attendance at an in-person hearing may be made by telephone by you and/or Lease Office Space, unless the arbitrator requires otherwise.</p>
	        	<p>The arbitrator will decide the substance of all claims in accordance with the laws of the State of Texas, including recognized principles of equity, and will honor all claims of privilege recognized by law. The arbitrator shall not be bound by rulings in prior arbitrations involving different Lease Office Space users, but is bound by rulings in prior arbitrations involving the same Lease Office Space user to the extent required by applicable law. The arbitrator's award shall be final and binding and judgment on the award rendered by the arbitrator may be entered in any court having jurisdiction thereof.</p>
	        	<p>13.5 Costs of Arbitration. Payment of all filing, administration and arbitrator fees will be governed by the AAA's rules, unless otherwise stated in this Agreement to Arbitrate.</p>
	        	<p>13.6 Severability. With the exception of any of the provisions in Section 13.3 of this Agreement to Arbitrate ("Prohibition of Class and Representative Actions and Non-Individualized Relief"), if an arbitrator or court decides that any part of this Agreement to Arbitrate is invalid or unenforceable, the other parts of this Agreement to Arbitrate shall still apply. If an arbitrator or court decides that any of the provisions in Section 13.3 of this Agreement to Arbitrate ("Prohibition of Class and Representative Actions and Non-Individualized Relief") is invalid or unenforceable, then the entirety of this Agreement to Arbitrate shall be null and void. The remainder of the Agreement and its Legal Disputes Section will continue to apply.</p>
	        	<p>13.7 Judicial Forum for Legal Disputes. Unless you and we agree otherwise, in the event that the Agreement to Arbitrate above is found not to apply to you or to a particular claim or dispute, either as a result of your decision to opt-out of the Agreement to Arbitrate or as a result of a decision by the arbitrator or a court order, you agree that any claim or dispute that has arisen or may arise between you and Lease Office Space must be resolved exclusively by a state or federal court located in Dallas, Texas. You and Lease Office Space agree to submit to the personal jurisdiction of the courts located within Dallas County, Texas for the purpose of litigating all such claims or disputes.</p>
	        	<p>13.8 Conflicts with Other Written Agreement; Exceptions. To the extent you have signed a written, wet or e-signature commercial agreement with Lease Office Space, the dispute resolution procedures in such agreement shall supersede the Dispute Resolution procedures herein, if applicable. Moreover, nothing in this Agreement prohibits Lease Office Space from seeking injunctive relief in federal or state court to the extent necessary to protect or enforce its intellectual property rights.</p>
	        	<p><b>14. Miscellaneous.</b></p>
	        	<p>Except for any agreements or policies explicitly referenced herein, this Agreement constitutes the complete and entire agreement between you and us as it pertains to the Site. We reserve all rights not granted in this Agreement. If any provision of this Agreement is held to be unenforceable for any reason, such provision will be reformed only to the extent necessary to make it enforceable, and such decision will not affect the enforceability of such provision under other circumstances, or of the remaining provisions hereof under all circumstances. You must be 18 years or older to use the Site.</p>
	        	<p>THIS AGREEMENT SHALL BE GOVERNED BY AND CONSTRUED IN ACCORDANCE WITH THE LAWS OF THE STATE OF TEXAS, USA, AS THOSE LAWS APPLY TO AGREEMENTS MADE AND SOLELY PERFORMED THEREIN. YOU IRREVOCABLY CONSENT TO AND WAIVE ALL OBJECTION TO PERSONAL JURISDICTION AND VENUE IN THE STATE AND FEDERAL COURTS AND ARBITRAL FORA LOCATED IN KING COUNTY, WASHINGTON, USA (SEATTLE). YOU AGREE TO NOT COMMENCE OR PROSECUTE ANY SUIT OR ACTION ARISING OUT OF OR RELATING TO THIS AGREEMENT OR THE SITE EXCEPT IN ACCORDANCE WITH THE TERMS OF THIS AGREEMENT, INCLUDING BUT NOT LIMITED TO THE AGREEMENT TO ARBITRATE.</p>
			</div>
		</div>		
<?php include 'footer.php'; ?>